# Use the official Node.js image as the base image
FROM node:slim AS development

# Set the working directory inside the container
WORKDIR /react_docker

# Copy package.json to the container
COPY package.json .

# Install dependencies
RUN npm install

# Copying all the files in our project
# . -> copy all the files present in host machine
# . -> copy from host machine to /react_docker this dir
COPY . .

# Expose port 5173 for development server
EXPOSE 5173

# Start the react development server with hot-reloading
CMD ["npm", "run", "dev"]