services:
  react_docker-dev:
    container_name: react_docker-container
    image: react_docker-dev-image
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/react_docker
      - /react_docker/node_modules
    command: npm run dev
